name: Bug Report
description: Report a bug or unexpected behavior in cidrly
title: '[Bug]: '
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below to help us resolve the issue quickly.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what went wrong...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. Enter input '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what should have happened...
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: input
    id: cidrly-version
    attributes:
      label: cidrly Version
      description: Run `cidrly --version` or `npm list cidrly`
      placeholder: 'e.g., 0.1.6'
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      description: Run `node --version`
      placeholder: 'e.g., v20.10.0'
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: Your OS and version
      placeholder: 'e.g., macOS 14.1, Ubuntu 22.04, Windows 11'
    validations:
      required: true

  - type: textarea
    id: network-plan
    attributes:
      label: Network Plan Details (Optional)
      description: If relevant, paste your network configuration (sanitize any sensitive data)
      placeholder: |
        {
          "rootCidr": "10.0.0.0/16",
          "subnetDesign": [...]
        }
      render: json

  - type: textarea
    id: error-logs
    attributes:
      label: Error Logs / Terminal Output
      description: Paste any error messages or relevant terminal output
      placeholder: Paste error messages here...
      render: shell

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: Add any other context or screenshots here...
