name: Documentation
description: Suggest improvements to documentation
title: "[Docs]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Help us improve cidrly's documentation!

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation needs improvement?
      options:
        - README
        - API Documentation
        - CLI Help / Usage Examples
        - Code Comments
        - Tutorial / Guide
        - Other
    validations:
      required: true

  - type: textarea
    id: what-needs-docs
    attributes:
      label: What Needs Documentation?
      description: What feature, concept, or functionality needs better documentation?
      placeholder: Describe what needs documentation...
    validations:
      required: true

  - type: textarea
    id: current-state
    attributes:
      label: Current State
      description: What's currently documented (if anything)?
      placeholder: |
        Current documentation says...
        There's no documentation for...

  - type: textarea
    id: proposed-improvement
    attributes:
      label: Proposed Improvement
      description: How should the documentation be improved?
      placeholder: Describe how it should be documented...
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context, examples, or references
      placeholder: Add any other context here...

  - type: checkboxes
    id: willing-to-contribute
    attributes:
      label: Contribution
      description: Would you be willing to contribute to this documentation?
      options:
        - label: I'm willing to submit a PR for this documentation
