name: Feature Request
description: Suggest a new feature or enhancement for cidrly
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please describe your idea below.

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see
      placeholder: Describe the feature...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem / Use Case
      description: What problem does this feature solve? What's the use case?
      placeholder: |
        I'm always frustrated when...
        This would help with...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How do you envision this feature working?
      placeholder: Describe how the feature should work...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or features?
      placeholder: Describe alternatives you've considered...

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or examples
      placeholder: Add any other context here...

  - type: checkboxes
    id: willing-to-contribute
    attributes:
      label: Contribution
      description: Would you be willing to contribute to this feature?
      options:
        - label: I'm willing to submit a PR for this feature
